language: python
os: linux
python:
  - "3.7"
node_js:
  - "12"
cache: pip
env:
  global:
    - secure: dn0FPQ5IG4M/3kdwnyI78ElQ308Vc3QnKAvkWfwMFb8QxDqxQdnTo7AV1qTMtbLrDNkeEWIgi4nc7jmXNtvGTwOfhAULVh6606Qs5B+ezTdwzajbbFMI8SKQx/pnTojOMu8dx7V4lMoR/YWcojR0VC1IWVC62TGbSB1k5BDGgH0=
    - DEFAULT_BRANCH: development
    - LANDING_PAGE: "http://localhost:8888/geppetto"
notifications:
  slack: metacell:5ALSeoP88DqIhORUJvxE56sq
install:
  - sudo apt-get install libgnutls28-dev
  - sudo apt install libcurl4-openssl-dev libssl-dev
  - sudo apt-get install python3-dev
script:
  - python utilities/install.py
  - ./NetPyNE-UI &
  - http_status=$(curl -s -I $1 $LANDING_PAGE | grep HTTP/1.1 | awk {'print $2'})
  - echo "$http_status"
  - cd tests/frontend/e2e
  - npm install
  - sleep 10 && travis_retry npm run test
  - exit 0