language: python
os: linux
sudo: false
dist: trusty
node_js:
  - "7"
env:
  global:
    secure: dn0FPQ5IG4M/3kdwnyI78ElQ308Vc3QnKAvkWfwMFb8QxDqxQdnTo7AV1qTMtbLrDNkeEWIgi4nc7jmXNtvGTwOfhAULVh6606Qs5B+ezTdwzajbbFMI8SKQx/pnTojOMu8dx7V4lMoR/YWcojR0VC1IWVC62TGbSB1k5BDGgH0=
install:
- git clone --quiet -b casper-tests https://github.com/MetaCell/geppetto-netpyne.git
- npm install --silent -g phantomjs 
- npm install --silent -g casperjs 
- npm install --silent -g slimerjs
- npm install --silent -g gl
python:
  - "2.7"
  - "3.5"
edge: true
notifications:
  slack: metacell:5ALSeoP88DqIhORUJvxE56sq
services:
  - docker
addons:
  firefox: "51.0"
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - export SLIMERJSLAUNCHER=/home/travis/firefox-51.0/firefox/firefox
  - export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/
    
script:
  - docker build -t="netpyne-ui" --build-arg netpyneuiBranch=$TRAVIS_BRANCH .
  - docker run  -t -dit --name=netpyne-ui_container -h localhost -p 8888:8888 netpyne-ui:latest
  - cd $TRAVIS_BUILD_DIR/ && ls
  - cd geppetto-netpyne && ls
  - ls
  - cd tests
  - bash utilities/netpyne-server-status.sh
  - sleep 30
  - http_status=$(curl -s -I $1 http://localhost:8888/geppetto | grep HTTP/1.1 | awk {'print $2'})
  - echo "$http_status"
  - while [ "$http_status" == "404" ]; do
      echo "Restart run";
      echo "Printing logs for debugging purposes";
      docker stop $(docker ps -a -q);
      docker rm $(docker ps -a -q);
      docker run  -t -dit --name=netpyne-ui_container -h localhost -p 8888:8888 netpyne-ui:latest
      bash utilities/netpyne-server-status.sh
      sleep 30;
      http_status=$(curl -s -I $1 http://localhost:8888/geppetto | grep HTTP/1.1 | awk {'print $2'})
      echo "Done restarting";
      echo "$http_status";
    done;
  - "curl -s -I $1 http://localhost:8888/geppetto | grep HTTP/1.1 | awk {'print $2'}"
  - curl http://localhost:8888/api/sessions
  - curl http://localhost:8888
  - curl http://localhost:8888/geppetto
  - xvfb-run -a --server-args="-screen 0 1024x768x24"  casperjs test netpyne-tests.js --host=http://localhost:8888/ --engine=slimerjs
  - sudo docker cp netpyne-ui_container:/home/jovyan/work/nrn-7.4/src/nrnpython/NetPyNE-UI-casper-tests/npm-debug.log /etc;
  - tail /etc/npm-debug.log -n 200
  - cd $TRAVIS_BUILD_DIR/ && tail netpyne-ui.log -n 200