# debian+miniconda3
FROM python:3.7-slim

# netpyne model from github
COPY init.py /opt/model/init.py
COPY ./mod/  /opt/model/mod/

# extract model name 
ENV LANG C.UTF-8

# install dependencies
RUN apt-get -qq update 
RUN apt-get install -y --no-install-recommends \
        g++ \
        libncurses-dev \
        autoconf \
        automake \
        make \
        flex \
        bison \
        unzip \
        wget

# Install latest NEURON
WORKDIR /opt
RUN wget https://neuron.yale.edu/ftp/neuron/versions/v7.6/7.6.2/nrn-7.6.2.tar.gz -P /opt/ -q \
        && tar -C /opt/ -xvzf nrn-7.6.2.tar.gz \
        && rm nrn-7.6.2.tar.gz

WORKDIR /opt/nrn-7.6
# RUN ./build.sh
RUN /bin/bash -c "./configure --prefix='/opt/neuron' --with-nrnpython=python3 --without-paranrn  --without-iv --without-nrnjava --without-x --without-nrnoc-x11"
RUN /bin/bash -c "make -s -j4"
RUN /bin/bash -c "make -s install -j4"

# Install NEURON-python
WORKDIR /opt/nrn-7.6/src/nrnpython
RUN /bin/bash -c "python setup.py install"
ENV PATH="/opt/neuron/x86_64/bin:${PATH}"

# install netpyne
WORKDIR /opt
RUN wget https://github.com/Neurosim-lab/netpyne/archive/development_py3.zip -P /opt/ -q\
        && unzip development_py3.zip -d /opt \
        && rm development_py3.zip
WORKDIR /opt/netpyne-development_py3
RUN /bin/bash -c "pip install --no-cache-dir -e ."

# compile mod files
WORKDIR /opt/model/mod
RUN /bin/bash -c "nrnivmodl"

# copy files
WORKDIR /opt/model
RUN /bin/bash -c "cp -R mod/x86_64 ./x86_64 && rm -R mod"

# cleaning
WORKDIR /opt
RUN apt-get purge -y --auto-remove autoconf automake autotools-dev binutils bison flex  m4 make perl perl-modules-5.24 unzip wget
RUN apt-get clean 
RUN rm -rf /var/lib/apt/lists/* \
        /tmp/*  \
        /var/tmp/* \
        /opt/nrn-7.6 \
        /opt/netpyne-development_py3/examples/ \
        /opt/netpyne-development_py3/doc/

# source env
CMD ["/bin/bash"]