FROM jupyter/base-notebook:latest
USER root
RUN apt-get -qq update
RUN apt-get -y install unzip
RUN apt-get -y install git-core
USER jovyan
RUN mkdir test
COPY *.py test/
WORKDIR test
RUN conda install -c conda-forge ipywidgets
RUN ls
RUN python install.py
CMD ./NEURON-UI
