FROM ghcr.io/puppeteer/puppeteer:16.1.0

# COPY webapp/package.json .
# COPY webapp/package-lock.json .

COPY tests/frontend/e2e/package.json .
COPY tests/frontend/e2e/package-lock.json .

RUN npm ci

USER pptruser
COPY --chown=pptruser:pptruser tests tests
# COPY --chown=pptruser:pptruser tests/frontend/e2e/jest.config.js .
# COPY --chown=pptruser:pptruser tests/frontend/e2e/jest-puppeteer.config.js .
# COPY --chown=pptruser:pptruser tests/frontend/e2e/babel.config.js .
# COPY --chown=pptruser:pptruser tests/frontend/e2e/tests/setupTests.js .


ENV TEST_URL=https://stage.netpyne.metacell.us/
