#!/bin/sh
CONFIG=$(pwd)/.jupyter-config
export JUPYTER_CONFIG_DIR=$CONFIG
exec jupyter notebook --NotebookApp.default_url=/geppetto --NotebookApp.token='' --library=netpyne_ui --NotebookApp.disable_check_xsrf=True
