#!/bin/sh
CONFIG=$(pwd)/.jupyter-config
export JUPYTER_CONFIG_DIR=$CONFIG
exec jupyter notebook --NotebookApp.default_url=/geppetto --NotebookApp.token='' --NotebookApp.notebook_dir=workspace --library=netpyne_ui --NotebookApp.disable_check_xsrf=True
