hub:
  image: 
    name: us.gcr.io/metacellllc/netpyne-hub
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

  allowNamedServers: true
  namedServerLimitPerUser: 2
  shutdownOnLogout: true

  extraConfig:
    timing: |
      c.JupyterHub.allow_named_servers = True
      c.Spawner.port = 8000
      c.Spawner.http_timeout = 300
      c.Spawner.start_timeout = 300
      c.Spawner.notebook_dir = '/home/jovyan/work/NetPyNE-UI'
      c.Spawner.default_url = '/geppetto'
      c.Spawner.debug = True
    spawner: >-
      c.Spawner.args = ["--library=netpyne_ui", "--NotebookApp.disable_check_xsrf=True"]

scheduling:
  userScheduler:
    replicas: 1

proxy:
  secretToken: ${{SECRET_TOKEN}}

auth:
  type: tmp

singleuser:
  storage:
    type: none
  memory:
    guarantee: 0.2G
  image:
    name:  us.gcr.io/metacellllc/netpyne-ui
    pullPolicy: IfNotPresent

cull:
  enabled: true
  users: false
  removeNamedServers: true
  timeout: 360
  every: 60
  concurrency: 10
  maxAge: 0

debug:
  enabled: false