#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/adrian/code/neuron/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/adrian/code/neuron/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/adrian/code/geppetto/NetPyNE-UI/netpyne_ui/tests/tut4/x86_64/.libs/libnrnmech.so" "$@"
