FROM ghcr.io/puppeteer/puppeteer:16.1.0



COPY package.json .
COPY package-lock.json .

RUN npm ci

USER pptruser
COPY --chown=pptruser:pptruser . .

USER $NB_UID
	
ENV TEST_URL=https://stage.netpyne.metacell.us/




