FROM ghcr.io/puppeteer/puppeteer:16.1.0

COPY package.json .
COPY package-lock.json .

RUN npm ci

USER node
COPY --chown=node:node . .

ENV TEST_URL=https://stage.netpyne.metacell.us/

# Add the following lines to change permissions
USER node




