#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _A_reg(void);
extern void _AMPA_reg(void);
extern void _AMPAr_reg(void);
extern void _GABAa_reg(void);
extern void _GABAar_reg(void);
extern void _GABAbr_reg(void);
extern void _H_reg(void);
extern void _HCN1_reg(void);
extern void _IC_reg(void);
extern void _IL_reg(void);
extern void _IL3_reg(void);
extern void _Iahp_reg(void);
extern void _MyExp2SynBB_reg(void);
extern void _MyExp2SynNMDABB_reg(void);
extern void _NMDA_reg(void);
extern void _NMDAr_reg(void);
extern void _Nca_reg(void);
extern void _OFThpo_reg(void);
extern void _OFThresh_reg(void);
extern void _ar_traub_reg(void);
extern void _cadad_reg(void);
extern void _cagk_reg(void);
extern void _cal_mh_reg(void);
extern void _cal_mig_reg(void);
extern void _can_mig_reg(void);
extern void _cat_mig_reg(void);
extern void _cat_traub_reg(void);
extern void _gabab_reg(void);
extern void _h_BS_reg(void);
extern void _h_harnett_reg(void);
extern void _h_kole_reg(void);
extern void _hsyn_reg(void);
extern void _ican_sidi_reg(void);
extern void _infot_reg(void);
extern void _izhi2007a_reg(void);
extern void _izhi2007b_reg(void);
extern void _kBK_reg(void);
extern void _kap_BS_reg(void);
extern void _kca_reg(void);
extern void _kdmc_BS_reg(void);
extern void _kdr2_reg(void);
extern void _kdr_BS_reg(void);
extern void _km_reg(void);
extern void _kmbg_reg(void);
extern void _kv_reg(void);
extern void _misc_reg(void);
extern void _na2_mh_reg(void);
extern void _naf2_reg(void);
extern void _nap_sidi_reg(void);
extern void _nax_BS_reg(void);
extern void _naz_reg(void);
extern void _nstim_reg(void);
extern void _ntIh_reg(void);
extern void _nthh_reg(void);
extern void _ntt_reg(void);
extern void _pregencv_reg(void);
extern void _samnutils_reg(void);
extern void _savedist_reg(void);
extern void _stats_reg(void);
extern void _vecst_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," A.mod");
    fprintf(stderr," AMPA.mod");
    fprintf(stderr," AMPAr.mod");
    fprintf(stderr," GABAa.mod");
    fprintf(stderr," GABAar.mod");
    fprintf(stderr," GABAbr.mod");
    fprintf(stderr," H.mod");
    fprintf(stderr," HCN1.mod");
    fprintf(stderr," IC.mod");
    fprintf(stderr," IL.mod");
    fprintf(stderr," IL3.mod");
    fprintf(stderr," Iahp.mod");
    fprintf(stderr," MyExp2SynBB.mod");
    fprintf(stderr," MyExp2SynNMDABB.mod");
    fprintf(stderr," NMDA.mod");
    fprintf(stderr," NMDAr.mod");
    fprintf(stderr," Nca.mod");
    fprintf(stderr," OFThpo.mod");
    fprintf(stderr," OFThresh.mod");
    fprintf(stderr," ar_traub.mod");
    fprintf(stderr," cadad.mod");
    fprintf(stderr," cagk.mod");
    fprintf(stderr," cal_mh.mod");
    fprintf(stderr," cal_mig.mod");
    fprintf(stderr," can_mig.mod");
    fprintf(stderr," cat_mig.mod");
    fprintf(stderr," cat_traub.mod");
    fprintf(stderr," gabab.mod");
    fprintf(stderr," h_BS.mod");
    fprintf(stderr," h_harnett.mod");
    fprintf(stderr," h_kole.mod");
    fprintf(stderr," hsyn.mod");
    fprintf(stderr," ican_sidi.mod");
    fprintf(stderr," infot.mod");
    fprintf(stderr," izhi2007a.mod");
    fprintf(stderr," izhi2007b.mod");
    fprintf(stderr," kBK.mod");
    fprintf(stderr," kap_BS.mod");
    fprintf(stderr," kca.mod");
    fprintf(stderr," kdmc_BS.mod");
    fprintf(stderr," kdr2.mod");
    fprintf(stderr," kdr_BS.mod");
    fprintf(stderr," km.mod");
    fprintf(stderr," kmbg.mod");
    fprintf(stderr," kv.mod");
    fprintf(stderr," misc.mod");
    fprintf(stderr," na2_mh.mod");
    fprintf(stderr," naf2.mod");
    fprintf(stderr," nap_sidi.mod");
    fprintf(stderr," nax_BS.mod");
    fprintf(stderr," naz.mod");
    fprintf(stderr," nstim.mod");
    fprintf(stderr," ntIh.mod");
    fprintf(stderr," nthh.mod");
    fprintf(stderr," ntt.mod");
    fprintf(stderr," pregencv.mod");
    fprintf(stderr," samnutils.mod");
    fprintf(stderr," savedist.mod");
    fprintf(stderr," stats.mod");
    fprintf(stderr," vecst.mod");
    fprintf(stderr, "\n");
  }
  _A_reg();
  _AMPA_reg();
  _AMPAr_reg();
  _GABAa_reg();
  _GABAar_reg();
  _GABAbr_reg();
  _H_reg();
  _HCN1_reg();
  _IC_reg();
  _IL_reg();
  _IL3_reg();
  _Iahp_reg();
  _MyExp2SynBB_reg();
  _MyExp2SynNMDABB_reg();
  _NMDA_reg();
  _NMDAr_reg();
  _Nca_reg();
  _OFThpo_reg();
  _OFThresh_reg();
  _ar_traub_reg();
  _cadad_reg();
  _cagk_reg();
  _cal_mh_reg();
  _cal_mig_reg();
  _can_mig_reg();
  _cat_mig_reg();
  _cat_traub_reg();
  _gabab_reg();
  _h_BS_reg();
  _h_harnett_reg();
  _h_kole_reg();
  _hsyn_reg();
  _ican_sidi_reg();
  _infot_reg();
  _izhi2007a_reg();
  _izhi2007b_reg();
  _kBK_reg();
  _kap_BS_reg();
  _kca_reg();
  _kdmc_BS_reg();
  _kdr2_reg();
  _kdr_BS_reg();
  _km_reg();
  _kmbg_reg();
  _kv_reg();
  _misc_reg();
  _na2_mh_reg();
  _naf2_reg();
  _nap_sidi_reg();
  _nax_BS_reg();
  _naz_reg();
  _nstim_reg();
  _ntIh_reg();
  _nthh_reg();
  _ntt_reg();
  _pregencv_reg();
  _samnutils_reg();
  _savedist_reg();
  _stats_reg();
  _vecst_reg();
}
