FROM metacell/jupyter-neuron:latest

USER root
# RUN apt-get install -y nodejs
# RUN npm install -g configurable-http-proxy
RUN conda install -c conda-forge nodejs configurable-http-proxy

USER $NB_USER

# feature_jupyterhub
ARG netpyneuiBranch=development 
ENV netpyneuiBranch=${netpyneuiBranch}  
RUN echo "$netpyneuiBranch";

ARG INCUBATOR_VER=unknown
RUN /bin/bash -c "INCUBATOR_VER=${INCUBATOR_VER} source activate snakes && pip install jupyterhub==0.9.4 jupyterhub-tmpauthenticator dockerspawner"

# Clone NetPyNE-UI and install the development version
RUN wget https://github.com/MetaCell/NetPyNE-UI/archive/$netpyneuiBranch.zip -q
RUN unzip $netpyneuiBranch.zip
WORKDIR /home/jovyan/work/NetPyNE-UI-$netpyneuiBranch/utilities
RUN /bin/bash -c "source activate snakes && python --version"
RUN /bin/bash -c "source activate snakes && exec python install.py branch $netpyneuiBranch"
WORKDIR /home/jovyan
RUN git clone https://github.com/Neurosim-lab/netpyne_workspace
WORKDIR /home/jovyan/netpyne_workspace
RUN ln -sfn /home/jovyan/work/NetPyNE-UI-$netpyneuiBranch/netpyne_ui/tests tests

# Copy jupyterhub_config
RUN cp /home/jovyan/work/NetPyNE-UI-$netpyneuiBranch/jupyterhub_config.py .

# we need to set up a password for jovyan or root user
CMD /bin/bash -c "source activate snakes && exec jupyterhub"







