FROM jupyterhub/jupyterhub:latest

# feature_jupyterhub
ARG netpyneuiBranch=feature_jupyterhub 
ENV netpyneuiBranch=${netpyneuiBranch}  
RUN echo "$netpyneuiBranch";

RUN pip install jupyterhub-tmpauthenticator dockerspawner

RUN wget https://raw.githubusercontent.com/MetaCell/NetPyNE-UI/$netpyneuiBranch/jupyterhub/jupyterhub_config.py -q
